#jwt:
#  secret: ldOcRiIgyRNKapQ88JSl8fLk7bn0BBK/snm8E9zVmL8=
#  expirationTimes:
#    access: 9999991800000 # 30분
#    refresh: 259200000 # 3일
#
#aws.rds:
#  url: board-db.cpuyggotahuc.ap-northeast-2.rds.amazonaws.com/borad?createDatabaseIfNotExist=true
#  id: root
#  pw: root1234

JWT_SECRET_KEY: ldOcRiIgyRNKapQ88JSl8fLk7bn0BBK/snm8E9zVmL8=
JWT_ACCESS_TOKEN_EXPIRATION_TIME: 9999991800000
JWT_REFRESH_TOKEN_EXPIRATION_TIME: 259200000

AWS_RDS_URL: board-db.cpuyggotahuc.ap-northeast-2.rds.amazonaws.com/borad?createDatabaseIfNotExist=true
AWS_RDS_USERNAME: root
AWS_RDS_PASSWORD: root1234
